import { auth, signIn, signOut } from "@/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen gap-4">
        <div>{JSON.stringify(session, null, 2)}</div>
        <form action={login}>
          <button>Log In</button>
        </form>
        <form action={logout}>
          <button>Log Out</button>
        </form>
        <button className="w-fit">
          <Link href={"/protected"}>Go to Protected Page</Link>
        </button>
        <button className="w-fit">
          <Link href={"/"}>Go to Home Page</Link>
        </button>
        {children}
      </body>
    </html>
  );
}

async function login() {
  "use server";
  await signIn();
}

async function logout() {
  "use server";
  await signOut();
}
